site_name: WiMoVE Documentation
site_url: https://wimove-oss.github.io/docs/
repo_name: WiMoVE-oss/docs
repo_url: https://github.com/WiMoVE-oss/docs
copyright: "🅭 🅯 🄎 Attribution-ShareAlike 4.0 <a href='https://creativecommons.org/licenses/by-sa/4.0/'>CC BY SA</a>"
extra:
  social:
    - link: https://github.com/WiMoVE-OSS/wimoved/
      icon: fontawesome/brands/github
theme:
  name: material
  features:
    - navigation.instant
    - navigation.indexes
    - content.code.copy
    - navigation.footer
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
nav:
  - Home: index.md
  - Architecture Overview:
    - architecture/index.md
  - Design Document: design/index.md
  - Setup Guide:
    - setup/index.md
    - Setup using Ansible: setup/ansible_setup.md
    - Manual Setup:
      - setup/manual/index.md
      - System Parameters: setup/manual/parameters.md
      - Access Point: setup/manual/access_point.md
      - Gateway: setup/manual/gateway.md
      - Route Reflector: setup/manual/route_reflector.md
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
