site_name: WiMoVE Documentation
site_url: https://wimove-oss.github.io/docs/
repo_name: WiMoVE-oss/docs
repo_url: https://github.com/WiMoVE-oss/docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.indexes 
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
nav:
  - Home: index.md
  - Architecture:
    - architecture/index.md
  - wimoved:
    - wimoved/index.md
    - Development Setup: wimoved/development.md
    - Cross Compiling: wimoved/cross_compiling.md
    - Monitoring and Logging: wimoved/monitoring_and_logging.md
  - Setup Guide:
    - setup/index.md
    - Access Point: setup/access_point.md
    - Gateway: setup/gateway.md
    - Route Reflector: setup/route_reflector.md
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
    



